### ISSUE TITLE
Demo link and more detailed explanation of how it works

### ISSUE THREAD

**Issue by oyeanuj** [deepakaggarwal7/react-social-login#1]
Hi @deepakaggarwal7, thank you for open-sourcing it! It looks very promising.

I was wondering - 
1. If you can share a more detailed explanation of how it works and/or the architecture as that will help better assess it compared to other options.

2. Do you plan to put up a demo link that once can test it more with?

Thanks!

**Comment by deepakaggarwal7** [comment]
Thanks. I plan to launch a quick usage video once I integrate Facebook as
well. Should be through with both by next weekend.

**Comment by oyeanuj** [comment]
Thanks @deepakaggarwal7! Looking forward to it - any documentation of how it works would be great :)

**Comment by oyeanuj** [comment]
@deepakaggarwal7 Just following up to see if you have had a chance to implement it and/or provide the video or documentation?

**Comment by deepakaggarwal7** [comment]
I've added Facebook as well. To try out demo, follow steps below:

1. Download the repo
2. Open react-social-login and replace
entry: './src/index.js',
  externals:{
    "react": "umd react"
  },
WITH
entry: './demo/index.js',
  /*externals:{
    "react": "umd react"
  }*/,
3. Set AppID for Google and/or Facebook in demo/demo.jsx
4. Run webpack
5. Run webpack-dev-server

You can access demo page as http://localhost:8080/webpack-dev-server/demo

You can change port by adding --port XXX in command at 4.

Will try to publish a video tutorial soon as well.
