### ISSUE TITLE
How to get extra fields from linkedin

### ISSUE THREAD

**Issue by bhaumik-gandhi** [deepakaggarwal7/react-social-login#106]
I would like to know if there is provision to get other fields from LinkedIn
like, need to see all fields that given by  "r_basicprofile"  by linkedin.

**Comment by deepakaggarwal7** [comment]
Currently, there's no provision. If you want to do so, you would need to fork out the source and append all additional required attributes in linkedin.js file. However, it raises an interesting thought to provide the ability to pass additional fields.
