### ISSUE TITLE
Facebook scope not working?

### ISSUE THREAD

**Issue by mindgrub-jkliphouse** [deepakaggarwal7/react-social-login#108]
Good afternoon!

I'm using the library per the example:

`<SocialButton
                            provider='facebook'
                            appId='<myappid>'
                            onLoginSuccess={this.handleSocialLogin}
                            onLoginFailure={this.handleSocialLoginFailure}
                            scope='user_photos'
                        >
                            Login with Facebook
                        </SocialButton>`

but the accessToken returned is not allowing the `user_photos` permission.  When I use the token from the graph explorer my code works fine.  Am I using your `scope` prop correctly?

Thanks!

**Comment by deepakaggarwal7** [comment]
scope='user_photos is the right way and it works. Could you revoke the access token from your facebook page for your app and try login. The permissions grant box should highlight that 

> "<YourAppName> will receive: your public profile, photos and email address."

If you do get this message you're getting photos permission.

**Comment by deepakaggarwal7** [comment]
Could you please confirm if the issue got resolved or add details? We plan to close this issue otherwise to clean up open issues. Thanks.
