### ISSUE TITLE
Remove console.log after successful login

### ISSUE THREAD

**Issue by Nova-DK** [deepakaggarwal7/react-social-login#11]
I think it should be up to the user of the package to log information. It looks unprofessional if you are constantly logging stuff that the plain user's eye shouldn't see or have use of.
At your index file, line 111, "console.log(res)" should be removed.

**Comment by nicolas-goudry** [comment]
You’re absolutely right!

Problem is, owner isn’t available since a while so you shouldn’t expect an update soon…

**Comment by deepakaggarwal7** [comment]
:) will update

**Comment by nicolas-goudry** [comment]
See https://github.com/deepakaggarwal7/react-social-login/pull/15

**Comment by deepakaggarwal7** [comment]
Fixed with #15 merge
