### ISSUE TITLE
how do I do to get age and gender 

### ISSUE THREAD

**Issue by zaw8phyo** [deepakaggarwal7/react-social-login#115]
I'm new to react. I don't know how can I do to get age and gender from facebook and google login. pls help.

**Comment by deepakaggarwal7** [comment]
you've to add needed scopes as described by providers.
For example, 
If you want birthday for facebook, add scope='user_birthday' property in the SocialButton tag
Or if you want from Google.
add scope='https://developers.google.com/identity/protocols/googlescopes'
