### ISSUE TITLE
LinkedIn 401 Error

### ISSUE THREAD

**Issue by pb-expa** [deepakaggarwal7/react-social-login#116]
Competent had been fine until just recently, now when logging in using LinkedIn, a 401 error is returned with the message that the access token has expired. We haven't changed configuration since deploying and Facebook/Google login still work just fine.

**Comment by deepakaggarwal7** [comment]
Demo still works for me and no change has been made to this component. Could you add more details on the error and/or provide the URL to try.

**Comment by deepakaggarwal7** [comment]
Feel free to re-open with more details.
