### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by kkrishnan90** [deepakaggarwal7/react-social-login#118]
This is by far the best library I've ever seen which shaves a ton of time for developers to integrate social logins. Thanks a ton for this @deepakaggarwal7 !

I would like to know the support or a library of the same for React Native..Any suggestion on this is much appreciated.
Thanks once again for this awesome library !

**Comment by deepakaggarwal7** [comment]
Did a good brainstorming around this. My initial preference was to leverage react-social-login only using a webview which seems doable with a few hacks. But, seems it would be much more cleaner of an approach to do it from scratch as I don't want mobile users to download React package just for this. I've been able to complete FB login and you'd get the first version with FB integrated soon. It's a WIP and the library would be react-native-social-login (younger brother to this one :D)

**Comment by smooJitter** [comment]
Which packages?  It appears the only thing required to make this work for react-native is <div>. to <View>.
