### ISSUE TITLE
Linkedin auth gives empty accessToken

### ISSUE THREAD

**Issue by MaxInMoon** [deepakaggarwal7/react-social-login#12]
Hi (and thank you for the repo!)

Got undefined `accessToken` and `expiresAt` on the returned `user` with Linkedin auth.

I tried with your demo, and in my app (not yet configured, but it works with google)
Will it work if the app is welled configured?

Thanks

**Comment by nicolas-goudry** [comment]
Hi,

Yeah it’s kinda _normal_ because we couldn’t find a way to get those info from LinkedIn login response. Will have to work on that soon.

**Comment by MaxInMoon** [comment]
Is it something we can do following the Linkedin [auth doc](https://developer.linkedin.com/docs/oauth2) or this is specific to something else?

**Comment by nicolas-goudry** [comment]
Yes, we have to dig deeper into LinkedIn Auth Doc in order to solve this.

I currently don’t have the time to look into it so if you think you can fix this, go ahead 😉 

Anyway next week I will be available to work on this!

**Comment by nicolas-goudry** [comment]
@MaxInMoon I rewrited RSL to a HOC, you can see merge request #17 where I added the `expiresAt` support for LinkedIn.

I also added `accessToken` on another branch – see [nicolas-goudry/react-social-login:fix/linkedin_accessToken](https://github.com/nicolas-goudry/react-social-login/tree/fix/linkedin_accessToken).

I’ll keep you updated about that as soon as I can.

**Comment by nicolas-goudry** [comment]
Fixed with `v3.1.0` update 🎊 

Can you please close?
