### ISSUE TITLE
Need token_id param from social_user object.

### ISSUE THREAD

**Issue by lakshmisanthi** [deepakaggarwal7/react-social-login#123]
Hi, thanks for features,

when I try to authenticate i am getting social_user object with _token,_profile,_provider, but I need token_id param, Is it possible to get that param with this package then how can I ?.

Thanks in advance.

**Comment by deepakaggarwal7** [comment]
Which provider are you using?

**Comment by deepakaggarwal7** [comment]
no response. closing it.
