### ISSUE TITLE
Facebook scopes permission issue

### ISSUE THREAD

**Issue by Mr-Bhardwa7** [deepakaggarwal7/react-social-login#124]
Getting message from facebook **"Sorry, something went wrong."** whenever I try to get permission of these scopes **"birthday,hometown,location,gender,age_range"**.

by concatenating my scopes in facebookScopes.
```
let facebookScopes = [
  'public_profile',
  'email',
  'birthday',
  'location',
  'gender',
  'hometown'
]
```

![screenshot from 2018-12-17 15-11-30](https://user-images.githubusercontent.com/40822939/50079261-2761da00-020f-11e9-87fa-f0c580fd6c01.png)

I tried these scope at faceebook tools explorer ( https://developers.facebook.com/tools/explorer/)  and here I've to generate new Access token by granting permissions.
 
**So the question is how can I take permission from user while login  ?**

**Comment by deepakaggarwal7** [comment]
You are using incorrect scopes. It should be user_birthday,user_hometown and so on.
refer https://developers.facebook.com/docs/facebook-login/permissions/ for exact scope wordings.
