### ISSUE TITLE
Does this module support Google+ New API for Sign in/up?

### ISSUE THREAD

**Issue by nisargrthakkar** [deepakaggarwal7/react-social-login#128]
Here is shout down update from Google https://developers.google.com/+/api-shutdown

**Comment by chrisregner** [comment]
If my understanding is correct, we should be fine.

> January 29: On January 29, we sent an email regarding projects that will be impacted by the Google+ API shutdown. The email stated that projects requesting the "plus.me" scope would be affected. _We would like to clarify that only projects directly requesting the "plus.me" scope are affected. This scope may have been listed in some emails, even if not directly requested._
Emphasis mine

*TL; DR:* Do you use `plus.me` scope? Yes --> remove it. No --> you're fine
Correct me if I'm wrong

**Comment by deepakaggarwal7** [comment]
We DO-NOT use Google+. Library would work as usual even after depreciation.
