### ISSUE TITLE
Linkedin login stop working. 

### ISSUE THREAD

**Issue by blgastesi** [deepakaggarwal7/react-social-login#129]
<img width="1489" alt="screen shot 2019-01-28 at 10 34 30" src="https://user-images.githubusercontent.com/30761712/51826854-58dac480-22e8-11e9-8ada-7a267ae6375c.png">

**Comment by blgastesi** [comment]
Maybe is related to this: https://engineering.linkedin.com/blog/2018/12/developer-program-updates

**Comment by deepakaggarwal7** [comment]
Could be a case. The JS SDK url itself says that JS SDK isn't supported (https://developer.linkedin.com/docs/getting-started-js-sdk). However, as blgastesi mentioned, ideally if it is supported until Mar 1, demo should have worked. I checked the versions, there doesn't seem to be any change. Looks like a LinkedIn issue only. What's worse is that there doesn't seem to be a JS SDK anymore ..

**Comment by dipesh008** [comment]
Hi @deepakaggarwal7 
any timeline to make this work?

I will really be helpful.

**Comment by deepakaggarwal7** [comment]
With LinkedIn deprecating their JS ask which this component leverages (as a
standard pattern), it isn't on radar. The solution will need something like
a proxy Oauth to be hosted as Linked can only be connected through server
Api and that Oauth provide JS ask to social auth.

**Comment by deepakaggarwal7** [comment]
LinkedIn deprecated its JS after Microsoft acquired it (Just like Instagram deprecated their JS sdk when Facebook acquired it). SocialAuth is all about leveraging providers JSSDK so it cannot be fixed as what we relied upon, doesn't exist from provider anymore. 
The only solution I could think of is to create a backend complementing OAuth component for SocialOauth which needs to be hosted as a separate API or as a route in your web-server.

Please vote your add thoughts in https://github.com/deepakaggarwal7/react-social-login/issues/193
