### ISSUE TITLE
Linked In TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by Jai-Kumaresh** [deepakaggarwal7/react-social-login#136]
Your [Demo](https://deepakaggarwal7.github.io/react-social-login/) Linked In login is not work in my browser.
I have error 
  ` TypeError: Cannot read property 'then' of undefined`

**Comment by Jai-Kumaresh** [comment]
@deepakaggarwal7 Can you help me.

**Comment by fcFn** [comment]
You should perhaps see #129. Also LinkedIn [no longer supports](https://developer.linkedin.com/docs/getting-started-js-sdk) Javascript SDK, so I don't think this will ever be fixed.

**Comment by mahanadarize** [comment]
TypeError: Cannot read property 'then' of undefined

please can you tell me why this kind of error is coming . only in LinkedIN I am getting this. Please tell me how to resolve this.

**Comment by deepakaggarwal7** [comment]
LinkedIn deprecated its JS after Microsoft acquired it (Just like Instagram deprecated their JS sdk when Facebook acquired it). SocialAuth is all about leveraging providers JSSDK so it cannot be fixed as what we relied upon, doesn't exist from provider anymore. 
The only solution I could think of is to create a backend complementing OAuth component for SocialOauth which needs to be hosted as a separate API or as a route in your web-server.

Please vote your add thoughts in https://github.com/deepakaggarwal7/react-social-login/issues/193
