### ISSUE TITLE
Lint error stops an app build, when using `run lint`

### ISSUE THREAD

**Issue by MaxInMoon** [deepakaggarwal7/react-social-login#14]
When I build my app using `yarn build`(=`npm run lint && webpack `),  a lint error raises and stops the build.

**Lint Error**

`Expected space or tab after '//' in comment`

**File concerned**

`react-social-login-master/src/index.js`, this [line](https://github.com/deepakaggarwal7/react-social-login/blob/master/src/index.js#L161)

**Comment by nicolas-goudry** [comment]
You shouldn’t lint your `node_modules` folder… But you’re right it’s a mistake 😄

**Comment by MaxInMoon** [comment]
I just understand what I did 😉, sorry!

**Comment by nicolas-goudry** [comment]
Will fix this as soon as I can 😉

**Comment by nicolas-goudry** [comment]
See https://github.com/deepakaggarwal7/react-social-login/pull/15

**Comment by nicolas-goudry** [comment]
@MaxInMoon Can you close the issue please? Thanks.
