### ISSUE TITLE
Consider removing react and bluebird from dependencies

### ISSUE THREAD

**Issue by jackyef** [deepakaggarwal7/react-social-login#140]
By moving `react` and `bluebird` to `peerDependencies`, this package could shave around ~24kB in bundlesize gzip.

I am new to this package, but is there any reason for these to be included as `react-social-login` own dependencies?

For `react`, in most cases we can just depend on the consumer to bring their own `react`.
For `bluebird`, unless this package is using specific method that aren't in the official `Promise` spec yet, we can rely on the consumer to polyfill their own `Promise`.

**Comment by thiago-soliveira** [comment]
I agree with this. Specially when things like [this](https://reactjs.org/warnings/invalid-hook-call-warning.html) happens.

**Comment by wattazoum** [comment]
@thiago-soliveira I imagine that, the fact that you are pointing this error out means that you got it on your project. Did you find a solution for that ?

**Comment by thiago-soliveira** [comment]
@wattazoum I did. I used yarn resolutions to fix this.

**Comment by deepakaggarwal7** [comment]
I've removed the bluebird need altogether and saw a whopping reduction from 120kb to 40KB.
