### ISSUE TITLE
LinkedIn Login is not working

### ISSUE THREAD

**Issue by abhisar1234** [deepakaggarwal7/react-social-login#152]
LinkedIn Login is not working

**Comment by wattazoum** [comment]
This may be due to #136

**Comment by dankleying** [comment]
Any updates?

**Comment by deepakaggarwal7** [comment]
LinkedIn deprecated its JS after Microsoft acquired it (Just like Instagram deprecated their JS sdk when Facebook acquired it). SocialAuth is all about leveraging providers JSSDK so it cannot be fixed as what we relied upon, doesn't exist from provider anymore. 
The only solution I could think of is to create a backend complementing OAuth component for SocialOauth which needs to be hosted as a separate API or as a route in your web-server.

Please vote your add thoughts in https://github.com/deepakaggarwal7/react-social-login/issues/193
