### ISSUE TITLE
FB.login() called before FB.init(). 

### ISSUE THREAD

**Issue by tufail** [deepakaggarwal7/react-social-login#153]
Please help , I am having issue with the sdk loading order. 
FB.login() called before FB.init().

**Comment by talmog** [comment]
I am using it on two pages with the same app, on one of them it loads correctly, the other gets this error.

**Comment by zamlahani** [comment]
I also got this issue because I mistyped "appId" prop as "appid"

**Comment by deepakaggarwal7** [comment]
Are you calling FB.init twice? Like in [this](https://stackoverflow.com/questions/4910974/error-fb-login-called-before-calling-fb-init) thread? It gets called in the component.

**Comment by multiwebinc** [comment]
You get this error when you use the default appId string (`YOUR_APP_ID`) instead of one from Facebook.

**Comment by deepakaggarwal7** [comment]
Looks like the issue is related to setting incorrect appid. Feel free to reopen this issue if this isn't the case. thanks  @zamlahani  and @multiwebinc  for adding details.
