### ISSUE TITLE
Facebook SDK Version Upgrade

### ISSUE THREAD

**Issue by dipesh008** [deepakaggarwal7/react-social-login#170]
Current this package is using Version 4 of FB SDK.
The latest is version 8.0 can you please update the FB SDK version to the latest v5.0. ( if you can do it v6.0 ) it will be best.

As FB has started showing active notifications  tp use v5.0 to use Privacy Features

![Screen Shot 2020-09-02 at 11 40 01 AM](https://user-images.githubusercontent.com/484903/91938145-1160b980-ed11-11ea-99a3-37051274102f.png)

**Comment by deepakaggarwal7** [comment]
This is fixed and will come in next version. I've upgraded to v5.0. However, now anyone can override facebook version by providing the version as props

   <SocialButton
          provider='facebook'
          appId='...'
          onLoginSuccess={this.onLoginSuccess}
          onLoginFailure={this.onLoginFailure}
          onLogoutSuccess={this.onLogoutSuccess}
          getInstance={this.setNodeRef.bind(this, 'facebook')}
          key={'facebook'}
          version={'v9.0'}
        >
