### ISSUE TITLE
Provide a callback on initialization/ do not render the button until the Google SDK is fully loaded

### ISSUE THREAD

**Issue by onecompiler-ops** [deepakaggarwal7/react-social-login#172]
Need to provide a call on successful initialization or stop rendering the button until the Google SDK is loaded properly. In slow network connections many of our users are facing the following issue 

<img width="1836" alt="Screenshot 2020-09-29 at 4 39 32 PM" src="https://user-images.githubusercontent.com/71093215/94551099-735e0180-0272-11eb-8d01-f7c3f3abcb75.png">

We can replicate this by keeping the Network as `Slow 3G` on chrome 

<img width="523" alt="Screenshot 2020-09-29 at 4 39 39 PM" src="https://user-images.githubusercontent.com/71093215/94551177-91c3fd00-0272-11eb-83bf-7373a824f193.png">

**Comment by onecompiler-ops** [comment]
I am able replicate the same on the demo website too (by keeping the network as Slow 3G on chrome)
![Uploading Screenshot 2020-09-29 at 5.08.32 PM.png…]()

**Comment by deepakaggarwal7** [comment]
This was fixed and released in the last build. Could you please check? It works for me on demo site now.

**Comment by deepakaggarwal7** [comment]
This was implemented in v3.4.10
