### ISSUE TITLE
How to call logout from other component and from other page url.

### ISSUE THREAD

**Issue by tufail** [deepakaggarwal7/react-social-login#174]
How to call logout from other component and from other page url.

Say: I have a login page with social button ( facebook login )-> clicking on this login success ->  landed on dashboard ->then I need to put logout link in navigation ..

Here I am missing doc how to logout the facebook because we can not ref to that button as it is not here in dashboard.
please help me

**Comment by deepakaggarwal7** [comment]
SocialLogin is simply a bridge to native SDKs. To call logout from a page
which doesn't have SocialLogin, you can try invoking SDK's logout like
window.FB.logout(()=>{handloe logout event here})

**Comment by rivaslive** [comment]
I have this same error, using Nextjs, when I start session I can see FB and gapi redeference in window, but when I reload these references they disappear, I think it would be great if you could provide a function like ʻimport SocialLogin, {onLogout} from "react-social -login ";` to easily log out from anywhere

**Comment by thanhtoan1196** [comment]
@rivaslive I agree with you
