### ISSUE TITLE
Need Opinion - Shall I https all SDKs?

### ISSUE THREAD

**Issue by deepakaggarwal7** [deepakaggarwal7/react-social-login#175]
Currently, SDK loading adapts the protocol of running applications. However, if your application is running under HTTP:// some SDKs fail to load as they do not entertain HTTP:// protocol. I'm thinking to explicitly make all SDKs https.

Does anyone feel concerned about this?

**Comment by quandaso** [comment]
No, because setup a local https is not quite easy. I see no problem to use https only

**Comment by MattRiddell** [comment]
Yeah agreed - maybe tell people to start react with `HTTPS=true yarn start` or whatever in the docs
