### ISSUE TITLE
Wrapper called when sdk is not loaded

### ISSUE THREAD

**Issue by prevostc** [deepakaggarwal7/react-social-login#176]
Hi,

I have an issue where my wrapper is rendered even if isLoaded is false.

Here is the codesandbox to reproduce: https://codesandbox.io/s/prod-tdd-les5b?file=/src/App.tsx

See below a hack to log state and render result, where we see the component getting rendered despite the state isLoaded being false.

<img width="1051" alt="Screenshot 2020-10-16 at 15 26 01" src="https://user-images.githubusercontent.com/998369/96263945-ef22b280-0fc3-11eb-9ed8-5de2e13d6ccd.png">

**Comment by deepakaggarwal7** [comment]
it was fixed.
