### ISSUE TITLE
React does not recognize the `triggerLogin` prop on a DOM element

### ISSUE THREAD

**Issue by murilorl** [deepakaggarwal7/react-social-login#180]
How do I get rid of this warning/error in the browser's console?
I have implemented it just like it's indicated in the [NPM page](https://www.npmjs.com/package/react-social-login), and every time I access the component where I have added my SocialLogin component I get the message in the console.

The login functionality is working with Facebook (the only one I have implemented so far) though...

**Comment by bruno-barros** [comment]
Same here. I'm working with Google and Facebook.
I tried to postpone the button mount, but no success.

`Warning: React does not recognize the `triggerLogin` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `triggerlogin` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by deepakaggarwal7** [comment]
As explained [here](https://reactjs.org/warnings/unknown-prop.html), unknown props shouldn't be added as attributes directly using {...props} to the element.

You need to extract method out of props.

 ```
   render() {
      const { children, triggerLogin, ...props } = this.props
        return (
            <button onClick={triggerLogin} {...props}>
              {children }
            </button>
        );
    }
}
```

Thanks for pointing it out. I'll update the docs. Try it please and confirm.

**Comment by bruno-barros** [comment]
This did the job.
Thank you very much.
