### ISSUE TITLE
Does this use Implicit flow or Authorization code with PKCE?

### ISSUE THREAD

**Issue by alpha-nome** [deepakaggarwal7/react-social-login#183]
I've been checking out the security concerns with using Implicit flow where we directly get the access token from the provider.

Just wanted to use this for my social auth and wanted to confirm how you are doing this.

Just so that you can quickly recollect,
Implicit flow: hit the provider with client id and they return access token in the redirect url.
Authorization code with PKCE: We hit provider with hash(string) + client Id, provider saves hash and returns code. Now, we hit provider with code, string, client id, we get access token in response.

Please do correct me if the above understanding is not correct. 

Thanks

**Comment by deepakaggarwal7** [comment]
We make use of respective provider SDKs under the hood. Hence, the handshake mechanism may vary based on how the SDK connect. Mostly, I see them using the Implcit flow.

**Comment by deepakaggarwal7** [comment]
Are you good for me to close this?

**Comment by alpha-nome** [comment]
Sure. Thanks
