### ISSUE TITLE
does not work with preact?

### ISSUE THREAD

**Issue by thanhtoan1196** [deepakaggarwal7/react-social-login#184]
does not work with preact?

![image](https://user-images.githubusercontent.com/16433547/103498729-4f651a00-4e78-11eb-867a-c5e5fbc8a2e9.png)

**Comment by deepakaggarwal7** [comment]
Haven't tried with preact. I've added the tag "Help Wanted" so that someone can investigate its compatibility and provide a fix.

**Comment by deepakaggarwal7** [comment]
Tried with preact. it works. Check this sandbox
https://codesandbox.io/s/long-cache-z1oh3?file=/src/index.js

**Comment by thanhtoan1196** [comment]
@deepakaggarwal7 thanks
