### ISSUE TITLE
How to reduce bundle size?

### ISSUE THREAD

**Issue by thanhtoan1196** [deepakaggarwal7/react-social-login#186]
How to reduce bundle size, it's too big for the rest

![image](https://user-images.githubusercontent.com/16433547/104979591-3db67180-5a37-11eb-8469-3193db956123.png)

**Comment by deepakaggarwal7** [comment]
Is this static or realtime analysis? I reckon, later. If that's true, it's likely to do with the FBSDK which is loaded in background and might be getting added to the 160kb of react-social-login.
ref:
https://www.freecodecamp.org/news/why-16-of-the-code-on-the-average-site-belongs-to-facebook-and-what-that-means-68956cd731be/#:~:text=This%20SDK%20code%20is%20so,on%20the%20average%20web%20page.&text=As%20a%20sizable%20and%20widely,average%20site%20today%20so%20big%3F

Could you please check and confirm?

**Comment by thanhtoan1196** [comment]
That is analyzer using @ next / bundle-analyzer with my app

**Comment by deepakaggarwal7** [comment]
Seems Bluebird promise library which this npm depends on is the culprit. If I take it off, size reduces from around 120kb to 40kb. Since it's extensively used, it might not be an easy path.
