### ISSUE TITLE
Why minify Javascript?

### ISSUE THREAD

**Issue by multiwebinc** [deepakaggarwal7/react-social-login#190]
This is more of a question since I'm not sure what the answer is, but I know that Webpack minifies JS by default, so why not just leave everything unminified to make debugging or viewing the source code easier? I haven't noticed any of the other packages in my node_modules folder that use minified JS.

I have this in my console:

![image](https://user-images.githubusercontent.com/901732/109058344-81d90980-76a8-11eb-9511-3cd40e30bb39.png)

Component `n`? What's that? Oh right, it's at column 92447 of the minified social-login.js file.

**Comment by deepakaggarwal7** [comment]
Interesting point. Yeah! I explored and found most packages not minified. Let me explore a bit on best practices. I'm sure minification was originally implemented as it was considered a best practice then but I read in a few places that it is getting irrelevant now as almost all dev uses one or the other minification for a final app which takes care of react-social-login (unless they are explicitly ignoring node_modules folder)

**Comment by deepakaggarwal7** [comment]
minification removed.
