### ISSUE TITLE
Instagram API has been changed

### ISSUE THREAD

**Issue by hdminh247** [deepakaggarwal7/react-social-login#192]
Currently, when I use Instagram authentication, it open this url 
`https://www.instagram.com/oauth/authorize/client_id=130209655678744&scope=basic&redirect_uri=https://localhost:3000/register?rslCallback=instagram&response_type=token`. 

It's not correct anymore. It should be `https://www.instagram.com/oauth/authorize/client_id=130209655678744&scope=user_profile&redirect_uri=https://localhost:3000/register?rslCallback=instagram&response_type=code`

**Comment by deepakaggarwal7** [comment]
Could you please confirm, the url you've mentioned is working for you? After facebook took over, I think a lot of stuff is deprecated.

**Comment by hdminh247** [comment]
> Could you please confirm, the url you've mentioned is working for you? After facebook took over, I think a lot of stuff is deprecated.

Yes, it's working very well on my side now

**Comment by deepakaggarwal7** [comment]
committed. will be available in next release.
