### ISSUE TITLE
Problems with react 17.0.1

### ISSUE THREAD

**Issue by injecteer** [deepakaggarwal7/react-social-login#194]
using 

```
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-social-login": "^3.4.12",
  },
```
In Firefox I'm getting:

> Uncaught (in promise) Error: [object Object]
    promise social-login.js:1
    promise callback*./node_modules/react-social-login/dist/social-login.js/</</t.default/<.promise< social-login.js:1
    default social-login.js:1
    value social-login.js:1
    React 6
    unstable_runWithPriority scheduler.development.js:646
    React 9
    js index.js:68
    js main.chunk.js:210
    Webpack 7

When the support for react 17.x is expected to be added?

**Comment by deepakaggarwal7** [comment]
It does support react 17.
https://codesandbox.io/s/react-social-login-h1tls

Maybe you can try upgrading to 3.4.13 or create a sandbox to help me debug it.

**Comment by dobladov** [comment]
I encountered a similar problem after trying to install the package with `npm` version 7, which is stricter with dependencies.

<img width="567" alt="Screenshot 2021-03-09 at 13 43 48" src="https://user-images.githubusercontent.com/1938043/110472379-93c1a000-80dd-11eb-89dd-bf8d3d91877e.png">

While it's true that the library support React 17, the `peerDependencies` are only referring to version 16: https://github.com/deepakaggarwal7/react-social-login/blob/master/package.json#L59

Here is an example of `peerDependencies` for multiple versions: https://github.com/anthonyjgrove/react-google-login/blob/master/package.json#L88

**Comment by deepakaggarwal7** [comment]
thanks @dobladov. I've used applied your suggested format.
