### ISSUE TITLE
Facebook dont working

### ISSUE THREAD

**Issue by JonhnyDev** [deepakaggarwal7/react-social-login#196]
follow:
facebook button on demo:
Mozilla:
![image](https://user-images.githubusercontent.com/43152652/110464060-6fe86500-80b1-11eb-91d8-b081ba250706.png)
Google CH:
![image](https://user-images.githubusercontent.com/43152652/110464232-aa520200-80b1-11eb-9f80-0afd28d43922.png)

Att: Login with LinkedIn dont working too

**Comment by deepakaggarwal7** [comment]
LinkedIn login doesn't works. LinkedIn login deprecated their JS SDK (after Microsoft takeover). Facebook one is a problem with demo as the appid isn't passed correctly. Will fix it. thanks for sharing!

**Comment by deepakaggarwal7** [comment]
fixed
