### ISSUE TITLE
Login With Amazon Not Working

### ISSUE THREAD

**Issue by ssriv068** [deepakaggarwal7/react-social-login#202]
We are experiencing technical difficult with login with amazon. Currently investigating the issue. We are seeing the following bad request.

![image](https://user-images.githubusercontent.com/19538791/119065496-b0b30300-b9ab-11eb-973d-8470fbb9de92.png)

**Comment by deepakaggarwal7** [comment]
It's working on [demo site](https://deepakaggarwal7.github.io/react-social-login/). Please try once again and update this thread.

**Comment by deepakaggarwal7** [comment]
I'm closing it. 400bad request is usually due to a mistake in API key. Feel free to reopen with details. It's working on demo site.
