### ISSUE TITLE
Update npm version and create a Gitter for better communication

### ISSUE THREAD

**Issue by nicolas-goudry** [deepakaggarwal7/react-social-login#21]
Hi @deepakaggarwal7,

Sorry to open this issue but there isn’t any way to contact you directly on your GitHub profile 😄 

Can you update RSL to version 3 on npm please ? This way we could definitely close issues #9, #10 and #12 😉 

Also, I think we should [open a Gitter community](https://gitter.im#createcommunity) (you can create a community from a repository) for better communication between contributors and providing help to users if they ask for 😃

**Comment by deepakaggarwal7** [comment]
Wasn't aware of Gitter.. Made an account.. 
Let me know if there's any settings needed in it.
