### ISSUE TITLE
Why does google take 2 secs initially to load on to the screen ?

### ISSUE THREAD

**Issue by jinojacob15** [deepakaggarwal7/react-social-login#217]

**Comment by karthikdivi** [comment]
@jinojacob15 Loading time we can't avoid, but what we can do is passing a LoaderComponent so that users can wait. 
I made the respective changes with this PR https://github.com/deepakaggarwal7/react-social-login/pull/219

**Comment by deepakaggarwal7** [comment]
Closing this. thanks @karthikdivi  for the loader.

**Comment by bobbyrinaldy** [comment]
@deepakaggarwal7 i cannot find any loader at the 2nd params, its not released yet ?
