### ISSUE TITLE
Logout doesn't seem to be working in demo

### ISSUE THREAD

**Issue by ballavamsi** [deepakaggarwal7/react-social-login#221]
In the demo, I logged in with a Google account then click on Logout once the profile information is displayed. If I click on login again it is not asking me to choose a profile it is directly taking the last used email.

**Comment by deepakaggarwal7** [comment]
Hi. I see the "choose account" option, every time I logout and click on the "Login with Google" button. Please check once and confirm if you are still seeing this issue. thanks

**Comment by ballavamsi** [comment]
It is working now.
