### ISSUE TITLE
Include callback for logout.

### ISSUE THREAD

**Issue by juveguevara** [deepakaggarwal7/react-social-login#23]
Hello,

Thanks for this package. Is there a possibility to include new callback for logout, i.e:

` <SocialButton`
`            provider='provider'`
`            appId='YOUR_APP_ID'`
`                  onLoginSuccess={handleSocialLogin}`
`                  onLoginFailure={handleSocialLoginFailure}`
`                  onLogout ={handleSocialLogout}`
`    >`

**Comment by nicolas-goudry** [comment]
Hi, thanks for your suggestion!

I’m afraid this feature won’t be supported by all providers but I’ll have a look at it tomorrow 😉

**Comment by juveguevara** [comment]
Thanks for looking at it. @nicolas-goudry  appreciate it.

**Comment by nicolas-goudry** [comment]
Reference (for further developments):
* [Amazon](https://developer.amazon.com/public/apis/engage/login-with-amazon/docs/javascript_sdk_reference.html#logout)
* [Facebook](https://developers.facebook.com/docs/reference/javascript/FB.logout)
* [Google](https://developers.google.com/api-client-library/javascript/reference/referencedocs#googleauthsignout)
* [LinkedIn section Additional SDK functions “Log the user out”](https://developer.linkedin.com/docs/getting-started-js-sdk)

Providers which doesn’t seem to support any kind of logout process:
* [GitHub](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps)
* [Instagram](https://www.instagram.com/developer/authentication)

**Comment by nicolas-goudry** [comment]
@juveguevara Just to clarify, the `handleSocialLogout` can’t exists without a `triggerLogout` prop (like `triggerLogin`), is that what you requested or am I wrong?

**Comment by juveguevara** [comment]
yes, that's exactly the request to have a Logout trigger that can be invoked when user would like to logout the social component in order to centralize it. thz
