### ISSUE TITLE
Warning: Can only update a mounted or mounting component ..

### ISSUE THREAD

**Issue by kamranahmedse** [deepakaggarwal7/react-social-login#25]
I am getting the below warning sometimes

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the SocialLogin component.
```

![image](https://user-images.githubusercontent.com/4921183/29314720-565a7ddc-81d0-11e7-80da-f755d50bc9d2.png)

not sure why but it seems to be thrown [at this line](https://github.com/deepakaggarwal7/react-social-login/blob/master/src/index.js#L71)

**Comment by nicolas-goudry** [comment]
Is it happening with all providers or a particular one?

I suspect that SDK's `load` promise resolves aflter component has been unmount... Maybe loading should be synchronous?

Can you try it?

**Comment by kamranahmedse** [comment]
I am using Facebook and Google and it seems to be happing when I have either of them in my form.

Actually, I have a redirect on my `componentWillMount` in my form where I check if the user is authenticated, if yes I redirect them somewhere else. If I remove this redirect and let the page load the error goes away.

**Comment by nicolas-goudry** [comment]
Yeah that's what I was afraid of, it's because when rsl `didMount`, we start the `load` promise which is sometimes resolved after rsl `didUnmount` because of your redirect.

I'll have a look at it as soon as I can, thanks for reporting!

**Comment by nicolas-goudry** [comment]
Hi @kamranahmedse, can you check [my branch](https://github.com/deepakaggarwal7/react-social-login/compare/master...nicolas-goudry:fix/unmount-while-loading) and tell me if it is the same ?

**Comment by kamranahmedse** [comment]
@nicolas-goudry sure, will check tonight and get back to you.
