### ISSUE TITLE
Amazon Login src address err

### ISSUE THREAD

**Issue by moloxiao** [deepakaggarwal7/react-social-login#26]
current is : http://api-cdn.amazon.com/sdk/login1.js 
may be right is : https://api-cdn.amazon.com/sdk/login1.js

i use current address meet err on chrome :  net::ERR_CONNECTION_REFUSED

**Comment by nicolas-goudry** [comment]
@moloxiao I just checked, as you can see from [source code](https://github.com/deepakaggarwal7/react-social-login/blob/master/src/sdk/amazon.js#L17), we just keep using the same protocol as the page.

Closing.

**Comment by all-iver** [comment]
In development my page is served using http.  Amazon will not serve their api over http, so should the link just be hardcoded to https?  Is there some way I can change it in config or provide the sdk manually?

**Comment by all-iver** [comment]
Never mind actually, I can just run over https.
