### ISSUE TITLE
What is currently supported?

### ISSUE THREAD

**Issue by advance512** [deepakaggarwal7/react-social-login#3]
I see Facebook and LinkedIn, also Google - but was it deprecated?

Seems like a nice project, a bit of a documentation cleanup would do it well!

**Comment by deepakaggarwal7** [comment]
They all are supported and I added support for LinkedIn as well (if you
download latest git code). I felt it was not pulling users. But my mojo
seems to resurrect with your comment :) Thanks. Will add more providers.
and surely do cleanup.

**Comment by advance512** [comment]
Great! Am watching and waiting for updates here :)

**Comment by deepakaggarwal7** [comment]
v2.0.0 is published with code refactored and working demo with Fb, Google and LinkedIn. Will add more documentations.

**Comment by advance512** [comment]
That is awesome!!!
