### ISSUE TITLE
Will it work on mobile web?

### ISSUE THREAD

**Issue by RajeshUppara** [deepakaggarwal7/react-social-login#31]
Thanks for awesome package. One thing want to know whether Will it work on mobile web ? how the pop window on mobile will be handled?

**Comment by nicolas-goudry** [comment]
Good question! I honestly don't know at all the answer, you'll have to try it to find out I guess...

Can you update us about this?

**Comment by nicolas-goudry** [comment]
@RajeshUppara Any news on this?

**Comment by nicolas-goudry** [comment]
@RajeshUppara Closing this as of my tests with the new [online demo](530411637301990), everything’s working fine with mobile web.
