### ISSUE TITLE
Google login can only work on 1st element

### ISSUE THREAD

**Issue by Vic-L** [deepakaggarwal7/react-social-login#32]
Hi,

I have multiple Google login buttons on the same screen, but only the first button can work; the subsequent button produced `SDK not loaded` error.

I am implementing it the same way as stated in the documentation.

Is there something I should take note of?

**Comment by adriencohen** [comment]
It seems like npm has not the latest version, you should try getting the library directly from github.

**Comment by nicolas-goudry** [comment]
Hi @Vic-L,

I just released 3.2 which contains this particular fix 🎊

**Comment by nicolas-goudry** [comment]
Same as #28
Fixed in [`3.2.0`](https://github.com/deepakaggarwal7/react-social-login/releases/tag/v3.2.0)

**Comment by Vic-L** [comment]
🙇
