### ISSUE TITLE
Amazon net::ERR_CONNECTION_REFUSED error

### ISSUE THREAD

**Issue by MMelouk** [deepakaggarwal7/react-social-login#37]
I am using a snippet very similar to the one in the demo files but for some reason, I am getting this error 

> GET http://api-cdn.amazon.com/sdk/login1.js net::ERR_CONNECTION_REFUSED`.

I have http://localhost:3000 & https://localhost:3000 both added to my allowed origins on Amazon's Security Profile Management. 
Browser used: Google Chrome Version 61.0.3163.100
react-social-login version: 3.2.0
```
<SocialButton
  provider='amazon'
  appId='amzn1.application-oa2-client.xxxxxxxxxxx'
  onLoginSuccess={handleSocialLogInSuccess}
  onLoginFailure={handleSocialLogInFailure}
>
  Login with Amazon
</SocialButton>
```

Any idea what might be the problem?

**Comment by nicolas-goudry** [comment]
Hi @MMelouk,

You are running your app over `http`, but Amazon Login service is only intended to work on `https`. Try to run your app over `https`, pretty sure it will work.

Keep us updated please 😉

**Comment by MMelouk** [comment]
@nicolas-goudry Worked! Thanks :)

**Comment by Nosajool** [comment]
For others that run into this issue and are using `create-react-app`, you can use https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#using-https-in-development
