### ISSUE TITLE
TypeError: this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by ramonfritsch** [deepakaggarwal7/react-social-login#38]
Getting this with React 16. Not sure if it was already there when I was using React 15.

```
SocialLogin error: TypeError: this.updater.enqueueCallback is not a function
    at SocialLogin../node_modules/react-social-login/node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState (ReactBaseClasses.js:64)
    at social-login.js:1344
    at <anonymous>
```

**Comment by nicolas-goudry** [comment]
Thanks for reporting, I'll dig it tomorrow :+1:

**Comment by nicolas-goudry** [comment]
Can you checkout my branch [`update/react`](https://github.com/nicolas-goudry/react-social-login/tree/update/react) and tell me if it's ok for you please!

**Comment by nicolas-goudry** [comment]
Any new on your side @ramonfritsch?

It has been merged into `develop` as it is working for me after updating, I’ll release it soon.

**Comment by ramonfritsch** [comment]
Yep, it seems to be solved on `develop`. Nice work!
