### ISSUE TITLE
Window is not defined error in nextjs

### ISSUE THREAD

**Issue by mira-thakkar** [deepakaggarwal7/react-social-login#39]
Hello i am using this package in my nextjs app for google and facebook login. my login page and social components are as follow. On Client side it is working fine. but when i reload the page, it is giving me error like "window is not defined"

social_login.js
```reactjs
 import React from 'react';
 import SocialLogin from 'react-social-login'; 
 import { connect } from 'react-redux' ;
 import {
  FACEBOOK_APP_ID,
  GOOGLE_APP_ID,
 } from '../../config';
 
 const SocialButton = SocialLogin(({ children, triggerLogin, ...props }) => (
   <button onClick={triggerLogin} {...props}>
     { children }
   </button>
 ));

 export default class Social {
   constructor(props){
      super(props);
      this.success = this.success.bind(this);
      this.fail = this.fail.bind(this);
   }

   success(data){
     console.log('success',data)
   }

   fail(data){
     console.log('success',data)
   }
   render(){
     return (
      <div className="social-auth-links text-center">
        <p>- OR -</p>
        <SocialButton
          className="btn btn-block btn-primary flat-corner"
          provider='facebook'
          appId={FACEBOOK_APP_ID}
          onLoginSuccess={props.success}
          onLoginFailure={props.fail}
          >
            <i className="fa fa-facebook" /> Sign up using Facebook
        </SocialButton>
        <SocialButton
          className="btn btn-block btn-danger flat-corner"
          provider='google'
          appId={GOOGLE_APP_ID}
          onLoginSuccess={this.success}
          onLoginFailure={this.props.fail}
        >
          <i className="fa fa-google-plus" /> Sign up using Google+
        </SocialButton>
      </div>
    );
  }
}
```

login.js

```
import React,{Component, PropTypes} from 'react';
import Social from '../components/social';
import Loginform from '../components/loginform';

class Login extends Component{
  constructor(props){
    super(props);
  }

  render(){
     return (
        <Loginform />
        <Social />
     );
  }
}

export default Login;
```

Is there any solution to work it on server side also ?

**Comment by nicolas-goudry** [comment]
Hi @mira-thakkar 

Can you please provide us with a repository reproducing this error?

**Comment by adriencohen** [comment]
Next.js use SSR so when you navigate to your login page not directly it works fine, but when you load directly the page Next.js will try to render the page server side so window is not defined.

You need to disable SSR with something like this (obviously you need to adapt this to your code)
`const SocialButton = dynamic(
  import('../../components/SocialButton'),
  { ssr: false },
);`

**Comment by mira-thakkar** [comment]
@nicolas-goudry i am using [zeit/next.js](https://github.com/zeit/next.js)

@adriencohen if i import using {ssr: false}, it will not load the social login component on server side.
I found the solution by dynamically importing that component in componentDidMount method, because at that time window is already defined. Anyway Thanks!

**Comment by nicolas-goudry** [comment]
Thanks @adriencohen for your help resolving this issue ;)
