### ISSUE TITLE
LinkedIn Login Gives Back Invalid Access Token

### ISSUE THREAD

**Issue by jakesorce** [deepakaggarwal7/react-social-login#49]
I'm trying to work with the Linkin Login. I get all of the data back which includes an access_token but when I try to make more API calls with that access_token LinkedIn is telling me that it is invalid. Any ideas?

**Comment by jakesorce** [comment]
Digging into this a little more I think you have some code in this package that is stripping a lot of the valid linkedin token out and only returning a portion of it. Hope that helps pin point the issue. Let me know if I can do anything to help

**Comment by nicolas-goudry** [comment]
Hi @jakesorce, can you please provide an example repository reproducing this bug? Thanks for reporting btw :+1:

**Comment by nicolas-goudry** [comment]
@jakesorce I just made a quick check about this, and it appears that the token produced through JS SDK is invalid through REST API. You have to use the JS SDK to make API calls then:
`window.IN.API.Raw('/people/~').result((res) => console.log(res))`

**Comment by jakesorce** [comment]
Sounds good. Thank you for this information. Just a heads up some of the README documentation is off. This would be a nice addition to the README fixes

**Comment by nicolas-goudry** [comment]
@jakesorce for sure I will add this particular point to doc. Can you point out any other information wrong or unclear please?
