### ISSUE TITLE
Facebook Scopes

### ISSUE THREAD

**Issue by jakesorce** [deepakaggarwal7/react-social-login#50]
Doesn't seem like there is a way to allow more scopes for Facebook so when I get my token back I have very limited access to the API. It would be nice if we could pass in allowed extra scopes for facebook so when I get the token I could for example post to my wall. Here is a reference of all the available scopes:

https://developers.facebook.com/docs/facebook-login/permissions/

**Comment by nicolas-goudry** [comment]
Hi @jakesorce,

This feature is available only for `google` provider but I intend to add same support for others soon.

Thanks for referencing fb doc about this. I'll add other providers doc references here so don't close this issue until it's released :+1:

**Comment by nicolas-goudry** [comment]
Reference:

- [Amazon](https://developer.amazon.com/docs/login-with-amazon/javascript-sdk-reference.html#authorize)
- [Facebook](https://developers.facebook.com/docs/facebook-login/permissions/)
- [GitHub](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/)
- [Google](https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2clientconfig)
- [Instagram](https://www.instagram.com/developer/authorization/)

LinkedIn doesn’t seem to have any option related to scopes/permissions.
