### ISSUE TITLE
Exception when internet connection is not there

### ISSUE THREAD

**Issue by aniruddhashevle** [deepakaggarwal7/react-social-login#55]
If I click on the social share button and internet connection is not there, I'm unable to handle this kinda exceptions.

**Comment by nicolas-goudry** [comment]
Nice spot :+1: I will try to work on that one for next release (2 to 3 weeks from now on) !

**Comment by aniruddhashevle** [comment]
@nicolas-goudry : Any updates on the above?

**Comment by deepakaggarwal7** [comment]
@aniruddhashevle  When internet is down, the authentication popup opens but the provider doesn't load. Eventually, user closes the popup. You can capture this event as illustrated in demo. However, the error is about permission denied. You can execute additional code to check internet connection and handle it to display some sort of a different popup. Does this helps?

**Comment by aniruddhashevle** [comment]
@deepakaggarwal7 : Yes of course we can do many work arounds for this, but it'd be great if we have built in feature for the same!

**Comment by deepakaggarwal7** [comment]
Better late than never. I've added a prop `func onInternetFailure()` which can be used to replace default Login() when internet is down. If this method returns false, default login code is skipped.
