### ISSUE TITLE
SDK not loaded when using google 

### ISSUE THREAD

**Issue by radjivF** [deepakaggarwal7/react-social-login#61]
Any Idea ? 

Cheers

**Comment by nicolas-goudry** [comment]
@radjivC Any error message? Steps to reproduce?

**Comment by radjivC** [comment]
That is the error message and when I follow the example. the error message is in the chrome console.

**Comment by nicolas-goudry** [comment]
Can you show a code sample please at least?

I can’t see from where this error is coming right now…

**Comment by yasharma** [comment]
@nicolas-goudry I am facing the same error when trying with google, however first time when button is clicked it shows error and second time it shows google login window. check https://github.com/yasharma/onlineRTI/blob/develop/src/components/Login/login.js

**Comment by yasharma** [comment]
@nicolas-goudry any help on this ??

**Comment by nicolas-goudry** [comment]
@yasharma This is so weird I can’t reproduce your issue guys…

Do you have an adblocker? I have to disable mine in order for RSL to work.
Are you using `http` or `https`?
Do you have any network request that fails in browser debugger?

The only reason for `SDK not loaded` error is that SDK’s `load` function never resolved or rejected.

Can you replace RSL code in `node_modules` with the one attached please? I’ve added some debug to Google provider and some timing. Maybe it can help you, but I’m not sure about this approach.

[social-login.zip](https://github.com/deepakaggarwal7/react-social-login/files/1587239/social-login.zip)

**Comment by singhxp** [comment]
I think the problem is when your running the code from you local box , the URL is http://localhost:8080
and this is not permitted by google Authorized JavaScript origins

For use with requests from a browser. This is the origin URI of the client application. It can't contain a wildcard (https://*.example.com) or a path (https://example.com/subdir). If you're using a nonstandard port, you must include it in the origin URI. 

I ran into to the same issue and fixed it by updating the host url
https://console.developers.google.com/apis/credentials/

**Comment by nicolas-goudry** [comment]
@radjivC @yasharma Can you please check that you followed [Google’s guide](https://developers.google.com/identity/sign-in/web/devconsole-project)? Also check that you allowed `https://localhost:8080` to your **Authorized JavaScript origins** and **Authorized redirect URI**

**Comment by haibo3318** [comment]
I also encountered this issue, seems the social login button loaded before Google SDK.

**Comment by radjivC** [comment]
@nicolas-goudry  I'm not working on the project anymore, sorry about that

**Comment by nicolas-goudry** [comment]
@haibo3318 Even if it was the case, you can't trigger SDK login function if SDK is not loaded...

**Comment by apascal** [comment]
I ran into the same issue and think it might come from blocked third-party cookies on my Chrome browser. The issue didn't occur on the same local dev host on another browser.

Regardless, the issue to me is that onLoginFailure() is called right after mounting the react-social-login component, rather than a different error - let's say - onLoadingFailure(), which would allow a proper handling.

**Comment by dilipMaharjan** [comment]
@apascal  did u solve your problem?

**Comment by NayanSrivastav** [comment]
This is happening constantly on mobile chrome, did someone got a soln or workaround?

**Comment by chandrasekhary** [comment]
I am getting the same issue for first time. Can you resolve it and suggest what i have to do

**Comment by leonardosalles** [comment]
in my case it was the domain, localhost was not listed in the whitelist for OAuth and Google SignIn api.

**Comment by onecompiler-ops** [comment]
@nicolas-goudry This is happening in production too, If internet is slow and by the time google js files loaded user clicks on login button, then this is happening. 
I think we should have a hook to see all required files loaded so that we can keep the button disabled till then

**Comment by bruno-silva5** [comment]
Any news?

**Comment by deepakaggarwal7** [comment]
Added loaded check. This works?
https://drive.google.com/file/d/1jpYZd4annGr76lmbahxpm_fYEfb_AMc2/view?usp=sharing

Yet to check-in!

**Comment by onecompiler-ops** [comment]
@deepakaggarwal7 appreciate your work. 
This solves the issues with slow networks.

**Comment by onecompiler-ops** [comment]
@deepakaggarwal7  We are not sure the new version `3.4.10` fixed the issue. 
We are able to replicate the issue in our website also in the demo page https://deepakaggarwal7.github.io/react-social-login/
It's showing the buttons before the SDK is loaded.

**Comment by deepakaggarwal7** [comment]
It does. Demo website wasn't updated. I've updated the build. Open a
browser -> set to slow3G and then hit
https://deepakaggarwal7.github.io/react-social-login/
You'll find buttons progressively appearing. Let me know if you have
issues.

**Comment by Marwa92** [comment]
@deepakaggarwal7  The problem appeared with me and the error appeared when i try to click on social buttons?
So, is there a way to do it by my self from code to check loading sdk?

**Comment by shivraj-geekologix** [comment]
@deepakaggarwal7 login with google button not appearing on first rendering, after that it appears. I facing this issue. Please help me resolve this issue.
