### ISSUE TITLE
Cant get even basic code working

### ISSUE THREAD

**Issue by drewmcmillan** [deepakaggarwal7/react-social-login#7]
```
import React from 'react';
import SocialLogin from 'react-social-login'

class FacebookLogin extends React.Component {
 
	responseFacebook(user, err) {
		console.log(user);
		console.log(err);
	}
 
	render() {
	  return (
	    <SocialLogin provider='facebook' appId='xxxxxxxxxxxxx' callback={this.responseFacebook}>
	  		<button>Login with Facebook</button>
	    </SocialLogin>
	  )
	}
}

export default FacebookLogin;
```

This gets me an error 
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `FacebookLogin`.
```

Any ideas why this is the case? Is it broken or is it me?

**Comment by nicolas-goudry** [comment]
I can't figure out why, but SocialLogin Component isn't exported as default, so it appears to be undefined the way you're loading it.

If you change this

```javascript
import SocialLogin from 'react-social-login'
```

by that

```javascript
import { SocialLogin } from 'react-social-login'
```

it will work.

---

Please keep in mind this is a library which is under development, it has been refactored recently but hasn't been released to npm yet, so you might expect some updates in near future 😉 

If you wish to, you're even free to contribute! 🎊

**Comment by deepakaggarwal7** [comment]
With 2.0.0, I'm not facing mentioned error even without using { }. Though I'm not sure what fixed this mysterious error, but seems to be working. Attached a link to working demo as comment isn't allowing to upload zip directly here.

[Working Demo With Your Code](http://s000.tinyupload.com/index.php?file_id=08863955027381729465)
