### ISSUE TITLE
Fetching user error.

### ISSUE THREAD

**Issue by lukojewel** [deepakaggarwal7/react-social-login#74]
index_bundle.js:112752 Fetching user
handleSocialLoginFailure @ index_bundle.js:112752
value @ index_bundle.js:58460
boundFunc @ index_bundle.js:55014
ReactErrorUtils.invokeGuardedCallback @ index_bundle.js:55020
executeDispatch @ index_bundle.js:45626
executeDispatchesInOrder @ index_bundle.js:45649
executeDispatchesAndRelease @ index_bundle.js:38372
executeDispatchesAndReleaseTopLevel @ index_bundle.js:38383
forEachAccumulated @ index_bundle.js:90395
processEventQueue @ index_bundle.js:38583
runEventQueueInBatch @ index_bundle.js:195383
handleTopLevel @ index_bundle.js:195393
handleTopLevelImpl @ index_bundle.js:195473
perform @ index_bundle.js:46316
batchedUpdates @ index_bundle.js:195245
batchedUpdates @ index_bundle.js:26325
dispatchEvent @ index_bundle.js:195548

Everything was working fine. suddenly stopped working when I reinstalled the node modules.

**Comment by nicolas-goudry** [comment]
Which version of RSL are you using ? Same question for React :+1:

**Comment by lukojewel** [comment]
Now i downgraded to 3.2.1. It is working fine. My react version is 15.5.4.

**Comment by nicolas-goudry** [comment]
This is a [*known* but not yet understanded bug](https://github.com/deepakaggarwal7/react-social-login/issues/60#issuecomment-341711424)

Please stick to 3.2.x or if you want 3.4.x you’ll also need react 16.x.

I’ll have to dig into this soon…

**Comment by nicolas-goudry** [comment]
Please follow #60 about this bug, closing now.
