### ISSUE TITLE
scope not working

### ISSUE THREAD

**Issue by bradeac** [deepakaggarwal7/react-social-login#76]
Hi,

The 'scope' property doesn't work for me. Maybe I'm doing something wrong ?

My code (the important bits):
```
import { OldSocialLogin as SocialLogin } from 'react-social-login';

class Login extends React.Component {
    response = (e) => {
        console.log(e._token.scope);
    }
    render() {
        return (
                        <SocialLogin
                        provider='google'
                        appId="appId"
                        scope="https://www.googleapis.com/auth/youtube"
                        callback={this.response}
                    >
                        <GoogleLoginButton text="Login with Google" />
                    </SocialLogin>
       );
   }
}
```

What I get in the console.log is: 
https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/plus.me openid email profile

I even tried 'youtube', 'youtube.readonly', but I get the same 'default' scopes.

Thanks 👍

**Comment by nicolas-goudry** [comment]
@bradeac Unfortunately, you’re using the old RSL component which doesn’t support latest features as scopes and logout…

It is working as expected with RSL HOC component. Closing this issue.
