### ISSUE TITLE
Google login doesn't work

### ISSUE THREAD

**Issue by Sotorin** [deepakaggarwal7/react-social-login#8]
How come Google login is commented out in demo apps and doesn't work? The only one that could have worked was LinkedIn. Facebook had some sort of error (couldn't even log in) and Google doesn't work at all (I'm mostly interested in that one). 

This could be good lib to use, provided that at least demos work :)

**Comment by nicolas-goudry** [comment]
This library is currently under refactoring and was kinda in "dev mode" when I started the refacto.

For example, you'll see in source code from NPM version that the Facebook app ID is hard-coded... This wasn't intended to be used widely at first.

I have fixed these issues with my last two PR, which have been merged but not yet released to NPM.

As far as I know, only Facebook and LinkedIn are supported for now and both works with the code on this repo (but not with the npm one which is not synced, yet).

Hope it helps, can't do better, sorry!

P.S. : until the release is done on NPM, maybe you could install from the Github repo directly?

```sh
$ npm i -S ssh+git@github.com:deepakaggarwal7/react-social-login.git#master
```

**Comment by Sotorin** [comment]
@nicolas-goudry - thanks for quick response. I'll follow your advice, it's a nice project and I could definitely use it!

**Comment by nicolas-goudry** [comment]
@Sotorin : v2 has been released!!! 🎊 You can fallback to npm version now 😃

**Comment by Sotorin** [comment]
@nicolas-goudry, thanks for the update. I'll check it out tomorrow!
