### ISSUE TITLE
linkedin error

### ISSUE THREAD

**Issue by jwisener** [deepakaggarwal7/react-social-login#87]
Closing decided to use something different than this component.

**Comment by nicolas-goudry** [comment]
This should not happen, do you have any other relevant logs?

**Comment by jwisener** [comment]
I greatly admire the work you've done, it's amazing to find this component. About the error above, If one just follows the written instructions on how to "use" the npm component you'll see this error.  I think the issue with the demo page that is in the source code, is it's within the actual code that holds component.

**Comment by jwisener** [comment]
Closing decided to use something different than this component.
