### ISSUE TITLE
linkedin error on reopen (from demo).

### ISSUE THREAD

**Issue by jwisener** [deepakaggarwal7/react-social-login#88]
Clicking the linkedin button, you only have one chance. If you close it and attempt to reopen you will get errors. 

![image](https://user-images.githubusercontent.com/135758/35170457-fe113b44-fd25-11e7-89c6-2cc18292f2e6.png)

![image](https://user-images.githubusercontent.com/135758/35170451-f751bf36-fd25-11e7-9b88-e7f918a3511d.png)

**Comment by nicolas-goudry** [comment]
Yeah, it's a **know bug** as we can't track SDK popup close event...

**Comment by jwisener** [comment]
Closing decided to use something different than this component.
