### ISSUE TITLE
Question : style for each provider

### ISSUE THREAD

**Issue by irongomme** [deepakaggarwal7/react-social-login#94]
Hi, 
Perhaps this is not the good place to ask, but I'm new to React and I don't how to style my buttons depending on providers. If I follow the sample, with a SocialButton component, where can I fetch the provider prop to make a conditionnal style on my button ?

**Comment by deepakaggarwal7** [comment]
I know its too late to reply. Unlike most libraries which "render" a button, react-social-login has no integrated view. It gives you a wrapper and you can put whatever component/style you want to add within it. In fact, this was the key reason for me to initiate this project as I used to be frustrated with the same question you had.
