### ISSUE TITLE
Support for Slack?

### ISSUE THREAD

**Issue by mhoffman** [deepakaggarwal7/react-social-login#97]
Hi 

very nice plugin and easy to set up in my experience. Are there any plans to support Slack as oauth provider? Would be quite to get group memberships.

Best,
Max.

**Comment by deepakaggarwal7** [comment]
Doesn't looks like Slack has a client library.  If you are aware of one, please share.

**Comment by deepakaggarwal7** [comment]
Closing this issue for now. Feel free to open with a hint for Slack. Thanks!
